// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: job-queue.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_encode JobType = 0
	JobType_decode JobType = 1
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "encode",
		1: "decode",
	}
	JobType_value = map[string]int32{
		"encode": 0,
		"decode": 1,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_job_queue_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_job_queue_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_job_queue_proto_rawDescGZIP(), []int{0}
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          JobType                `protobuf:"varint,1,opt,name=type,proto3,enum=api.JobType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_job_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_job_queue_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_encode
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          JobType                `protobuf:"varint,2,opt,name=type,proto3,enum=api.JobType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_job_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_job_queue_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_encode
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_job_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_job_queue_proto_rawDescGZIP(), []int{2}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_job_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_job_queue_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

var File_job_queue_proto protoreflect.FileDescriptor

const file_job_queue_proto_rawDesc = "" +
	"\n" +
	"\x0fjob-queue.proto\x12\x03api\"4\n" +
	"\x10SubmitJobRequest\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.api.JobTypeR\x04type\"L\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12 \n" +
	"\x04type\x18\x02 \x01(\x0e2\f.api.JobTypeR\x04type\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"^\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress*!\n" +
	"\aJobType\x12\n" +
	"\n" +
	"\x06encode\x10\x00\x12\n" +
	"\n" +
	"\x06decode\x10\x012\x8a\x01\n" +
	"\bJobQueue\x12:\n" +
	"\tSubmitJob\x12\x15.api.SubmitJobRequest\x1a\x16.api.SubmitJobResponse\x12B\n" +
	"\x0fStreamJobStatus\x12\x15.api.JobStatusRequest\x1a\x16.api.JobStatusResponse0\x01B8Z6github.com/YOUR-GITHUB-USERNAME/type-safe-go-react/apib\x06proto3"

var (
	file_job_queue_proto_rawDescOnce sync.Once
	file_job_queue_proto_rawDescData []byte
)

func file_job_queue_proto_rawDescGZIP() []byte {
	file_job_queue_proto_rawDescOnce.Do(func() {
		file_job_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_queue_proto_rawDesc), len(file_job_queue_proto_rawDesc)))
	})
	return file_job_queue_proto_rawDescData
}

var file_job_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_job_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_job_queue_proto_goTypes = []any{
	(JobType)(0),              // 0: api.JobType
	(*SubmitJobRequest)(nil),  // 1: api.SubmitJobRequest
	(*SubmitJobResponse)(nil), // 2: api.SubmitJobResponse
	(*JobStatusRequest)(nil),  // 3: api.JobStatusRequest
	(*JobStatusResponse)(nil), // 4: api.JobStatusResponse
}
var file_job_queue_proto_depIdxs = []int32{
	0, // 0: api.SubmitJobRequest.type:type_name -> api.JobType
	0, // 1: api.SubmitJobResponse.type:type_name -> api.JobType
	1, // 2: api.JobQueue.SubmitJob:input_type -> api.SubmitJobRequest
	3, // 3: api.JobQueue.StreamJobStatus:input_type -> api.JobStatusRequest
	2, // 4: api.JobQueue.SubmitJob:output_type -> api.SubmitJobResponse
	4, // 5: api.JobQueue.StreamJobStatus:output_type -> api.JobStatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_job_queue_proto_init() }
func file_job_queue_proto_init() {
	if File_job_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_queue_proto_rawDesc), len(file_job_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_queue_proto_goTypes,
		DependencyIndexes: file_job_queue_proto_depIdxs,
		EnumInfos:         file_job_queue_proto_enumTypes,
		MessageInfos:      file_job_queue_proto_msgTypes,
	}.Build()
	File_job_queue_proto = out.File
	file_job_queue_proto_goTypes = nil
	file_job_queue_proto_depIdxs = nil
}
